import Head from "next/head";
import { Inter } from "@next/font/google";
import { GetServerSideProps } from "next";

const inter = Inter({ subsets: ["latin"] });

import Editor from "../components/Editor";
import { useEffect, useState } from "react";

import { encode, decode, getCurrentLink } from "../utils/parse";
import Article from "../components/Article";

export default function Home({ decoded }: { decoded: string }) {
	let code = `function define() {
    const name = "Yashas Bhat"
    const hello = "WHat do uou mean?"
  
    return function() {
      return name + hello
    }
  }
const x = define()
console.log(x("name"))`;
	const [encoded, setEncoded] = useState(encode(code));
	const [share, setShare] = useState("");

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={inter.className}>
				<div className="prose prose-sm p-3 mx-auto">
					<div className="mt-4 md:mt-16">
						<Article share={encoded} />
					</div>
				</div>
				<div className="code-box">
					<Editor
						code={decoded || code}
						cb={(v: string, l) => {
							setEncoded(v);

							// this is necessary to make sure we're not one update behind while updating state
							setEncoded((v) => {
								console.log(v);
								return encode(v);
							});
						}}
					/>
				</div>
			</main>
		</div>
	);
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
	if (req.url === undefined) {
		return {
			props: {
				decoded: "",
			},
		};
	}
	const encoded = req?.url.split("/?code=")[1];

	let decoded = decode(encoded);

	return {
		props: {
			decoded,
		},
	};
};
